export const mockLandingConsultants = [
  {
    profilePictureUrl: "https://randomuser.me/api/portraits/men/13.jpg",
    name: "John Doe",
    topic: "Web Development",
    hourlyRate: 75,
    averageRating: 4.5,
    numberOfRatings: 10,
  },
  {
    profilePictureUrl: "https://randomuser.me/api/portraits/women/79.jpg",
    name: "Jane Smith",
    topic: "Graphic Design",
    hourlyRate: 50,
    averageRating: 3.8,
    numberOfRatings: 5,
  },
  {
    profilePictureUrl: "https://randomuser.me/api/portraits/men/42.jpg",
    name: "Michael Johnson",
    topic: "Mobile App Development",
    hourlyRate: 90,
    averageRating: 4.2,
    numberOfRatings: 8,
  },
  {
    profilePictureUrl: "https://randomuser.me/api/portraits/women/18.jpg",
    name: "Emily Davis",
    topic: "UI/UX Design",
    hourlyRate: 60,
    averageRating: 4.0,
    numberOfRatings: 12,
  },
  {
    profilePictureUrl: "https://randomuser.me/api/portraits/men/87.jpg",
    name: "David Wilson",
    topic: "Data Science",
    hourlyRate: 100,
    averageRating: 4.8,
    numberOfRatings: 15,
  },
  {
    profilePictureUrl: "https://randomuser.me/api/portraits/women/63.jpg",
    name: "Olivia Thompson",
    topic: "Digital Marketing",
    hourlyRate: 70,
    averageRating: 4.6,
    numberOfRatings: 7,
  },
  {
    profilePictureUrl: "https://randomuser.me/api/portraits/men/55.jpg",
    name: "Daniel Anderson",
    topic: "Cybersecurity",
    hourlyRate: 80,
    averageRating: 4.4,
    numberOfRatings: 9,
  },
  {
    profilePictureUrl: "https://randomuser.me/api/portraits/women/32.jpg",
    name: "Sophia Martinez",
    topic: "Content Writing",
    hourlyRate: 55,
    averageRating: 3.9,
    numberOfRatings: 6,
  },
  {
    profilePictureUrl: "https://randomuser.me/api/portraits/men/71.jpg",
    name: "Matthew Taylor",
    topic: "Software Engineering",
    hourlyRate: 95,
    averageRating: 4.7,
    numberOfRatings: 11,
  },
  {
    profilePictureUrl: "https://randomuser.me/api/portraits/women/47.jpg",
    name: "Ava Clark",
    topic: "Product Management",
    hourlyRate: 85,
    averageRating: 4.3,
    numberOfRatings: 13,
  },
  {
    profilePictureUrl: "https://randomuser.me/api/portraits/men/24.jpg",
    name: "James Rodriguez",
    topic: "Machine Learning",
    hourlyRate: 110,
    averageRating: 4.9,
    numberOfRatings: 14,
  },
  {
    profilePictureUrl: "https://randomuser.me/api/portraits/women/91.jpg",
    name: "Mia Harris",
    topic: "Social Media Marketing",
    hourlyRate: 65,
    averageRating: 4.1,
    numberOfRatings: 7,
  },
];
